name: Welcome contributors

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hello there ${{ github.actor }} 👋

          Welcome to oc-frontend !!💖🥳

          Thank you 🎉 for opening an issue in this project. oc-frontend fosters an open and welcoming environment for all our contributors.🌸

          Please take care of few points : Clearly specify the title and description of the issue . You can even add supporting material like Screenshots etc.

          Incase you want to claim this issue, please tag the maintainers by commenting down below! We will try to get back to you as soon as we can.👀

          👩‍💻 If you have any interesting ideas, just open an issue. We would love to hear you and engage in discussions.

        pr-message: |
          Hello there ${{ github.actor }} 👋

          Thank you and congrats 🎉 for opening a PR in this project.✨

          oc-frontend fosters an open and welcoming environment for all our contributors.🌸

          Please take care of few points : Clearly specify the title and description of the Pull Request . Specify the issue no using " #[issue_no] "

          Please tag the maintainers by commenting down below! We will review it as soon as we can.👀


